set(source_list ${source_list}
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_exti.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c
${PROJ_PATH}/Src/Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c
${PROJ_PATH}/Src/Core/Src/tim.c
${PROJ_PATH}/Src/Core/Src/gpio.c
${PROJ_PATH}/Src/Core/Src/stm32f0xx_hal_msp.c
${PROJ_PATH}/Src/Core/Src/system_stm32f0xx.c
${PROJ_PATH}/Src/Core/Src/dma.c
${PROJ_PATH}/Src/Core/Src/adc.c
${PROJ_PATH}/Src/Core/Src/main.c
${PROJ_PATH}/Src/Core/Src/stm32f0xx_it.c
${PROJ_PATH}/Src/Core/Src/can.c
${PROJ_PATH}/Src/startup_stm32f091xc.s
)
